name: preprocessed_data
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=4.1.3
  - seaborn=0.13.2
  - pandas=2.3.2
  - pip=24.3.1
  #- ydata-profiling=4.10.0
  - pyarrow=21.0.0
  - ipython>=8,<9 # Fix issues with printing pretty html, another update to this due to "cannot import name 'display' from 'IPython.core.display"
  - ipywidgets>=8 # to fix issues with jupyerlab not working outside container
  - jupyterlab_widgets # to fix issues with jupyerlab not working outside container
  - tqdm # to fix issues with jupyerlab not working outside container
  - pip:
      - wandb==0.21.3


# will want to update my run command from 'mlflow run .' to 'mlflow run . --env-manager=conda'
